fixed adduser

diff --git a/bin.sym/adduser b/bin.sym/adduser
--- a/bin.sym/adduser
+++ b/bin.sym/adduser
@@ -1,17 +1,14 @@
 #!/bin/bash
 # Script to add a user to Linux system
 if [ "$(id -u)" -eq 0 ]; then
-    read -p -r "enter username : " username
-    read -s -r -p "enter password : " password
-    egrep "^$username" /etc/passwd >/dev/null
-    if [ $? -eq 0 ]; then
-        echo -e "\n$username already exists"
-        exit 1
-    else
-        pass=$(perl -e 'print crypt($ARGV[0], "password")' "$password")
-        useradd -m -p "$pass" "$username"
-        [ $? -eq 0 ] && echo -e "\nUser successfully added" || echo -e "\nFailed to add user"
-    fi
+    echo "Enter username: "
+    read -r username
+    echo "Enter password: "
+    read -rs password
+    egrep "^$username" /etc/passwd >/dev/null && echo -e "\n$username already exists" && exit 1
+
+    pass=$(perl -e 'print crypt($ARGV[0], "password")' "$password")
+    useradd -m -p "$pass" "$username" && echo -e "\nUser successfully added" || echo -e "\nFailed to add user"
 else
     echo "script must be run as root"
     exit 2
