testscript update

diff --git a/bin.sym/testscripts b/bin.sym/testscripts
--- a/bin.sym/testscripts
+++ b/bin.sym/testscripts
@@ -2,16 +2,23 @@
 set -e
 set -o pipefail
 
-if [ "$1" ]; then
-    shellcheck "$1" && echo "[OK]: successfully linted $1"
-    exit 0
-fi
+ERRORS=()
 
-(
 # find all executables and run `shellcheck`
 for f in $(find . -type f -not -iwholename '*.git*' | sort -u); do
 	if file "$f" | grep --quiet shell; then
-		shellcheck "$f" && echo "[OK]: sucessfully linted $f"
+		{
+			shellcheck "$f" && echo "[OK]: sucessfully linted $f"
+		} || {
+			# add to errors
+			ERRORS+=("$f")
+		}
 	fi
 done
-)
+
+if [ ${#ERRORS[@]} -eq 0 ]; then
+	echo "No errors!"
+else
+	echo "These files failed shellcheck: ${ERRORS[*]}"
+	exit 1
+fi
